[[pages]]
path = "web/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "web/chat.py"
name = "Research Chat with PDF Upload"
icon = "ğŸ”"

[[pages]]
path = "web/search.py"
name = "Searching Paper"
icon = "ğŸŒ"

[[pages]]
path = "web/translate.py"
name = "PDF Translator"
icon = "ğŸ“–"

[[pages]]
path = "web/plagiarism.py"
name = "Plagiarism Detection"
icon = "ğŸ“–"

[[pages]]
path = "web/contact.py"
name = "Contact"
icon = "ğŸ“§"