[[pages]]
path = "web/chat.py"
name = "Research Chat with PDF Upload"
icon = "ğŸ”"

[[pages]]
path = "web/search.py"
name = "Searching Paper"
icon = "ğŸŒ"

[[pages]]
path = "web/visual.py"
name = "Visual Literature Mapping"
icon = "ğŸ“Š"

[[pages]]
path = "web/translate.py"
name = "PDF Translator"
icon = "ğŸ“–"

