[[pages]]
path = "web/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "web/chat.py"
name = "Retriever Research QnA"
icon = "ğŸ”"

[[pages]]
path = "web/search.py"
name = "Paper Finder+"
icon = "ğŸŒ"

[[pages]]
path = "web/translate.py"
name = "Expert Translator"
icon = "ğŸ“–"

[[pages]]
path = "web/plagiarism.py"
name = "Plagiarism Detection"
icon = "ğŸ”"

[[pages]]
path = "web/writing.py"
name = "Writing Assistant"
icon = "âœï¸"

[[pages]]
path = "web/contact.py"
name = "Contact"
icon = "ğŸ“§"